services:
  nginx:
    image: nginx
    ports:
      - 80:80
    environment:
      - NGINX_HOST=${HOST_NAME}
      - NGINX_PORT=${HOST_PORT}
    volumes:
      - ./dotori.conf:/etc/nginx/sites-enabled/dotori.conf
    depends_on:
      - backend
  backend:
    build: backend
