version: '3.8'
services:
  nginx:
    image: nginx:latest
    expose:
      - 80:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - dotori_network
  networks:
    dotori_network:
